name: Newsletter populator

on:
  workflow_dispatch:
    inputs:
      week:
        description: 'The Week whose sections should be generated. Should be A or B.'
        required: true
        default: 'A'

jobs:
  generate-newsletter:
    environment: prod
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run newsletter populator
      env:
        API_KEY: ${{ secrets.API_KEY }}
        BASE_URL: ${{ vars.BASE_URL }}
      run: python newsletter_populator.py ${{ github.event.inputs.week }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: output-artifacts
        path: output
